### GET ALL
GET http://localhost:8080/api/games

### GET ONE
GET http://localhost:8080/api/games/1

### CREATE
POST http://localhost:8080/api/games/ HTTP/1.1
Content-Type: application/json

{
    "name":"name",
    "description":"description",
    "settings":{
        "a":"b",
        "c":[
                {"name":"d","value":5},
                {"name":"d","value":5}
            ]
        },
    "imageURL":"www...",
    "genre":"fuun"
}

